name: Deploy Site
on:
  push:
    paths:
      - "picea/frontend/**"

jobs:
  Deploy:
    name: AWS Deploy website 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: us-east-1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Download Dependencies
        run: |
          cd ./picea/frontend
          npm install

      - name: Build
        run: |
          cd ./picea/frontend
          npm run build
        env: 
          CI: false

      - name: Sync with AWS S3
        run: aws s3 cp build s3://picea --recursive

      - name: CloudFront Invalidation
        run: aws cloudfront create-invalidation --distribution-id E10YAOSPP5PEZ6 --paths "/*"